### ISSUE TITLE
Error calling sync_deps.py

### ISSUE THREAD

**Issue by mariecwhite** [openxla/openxla-pjrt-plugin#185]
When calling `sync_deps.py`, I get the error:

```
fatal: remote error: upload-pack: not our ref db41915fc548f2c25a03a860cc2a2f5da3806aae
Errors during submodule fetch:
    third_party/mlir-hlo
Traceback (most recent call last):
  File "/home/mariewhite/github/iree-samples/openxla-pjrt-plugin/./sync_deps.py", line 127, in <module>
    main()
  File "/home/mariewhite/github/iree-samples/openxla-pjrt-plugin/./sync_deps.py", line 79, in main
    run(fetch_args, repo_dir)
  File "/home/mariewhite/github/iree-samples/openxla-pjrt-plugin/./sync_deps.py", line 121, in run
    raise RuntimeError(f"Git command failed: {args_text} (from {cwd})"
```

The script assumes a fresh build. This is fixed if the iree directory is manually deleted before calling `sync_deps.py`

**Comment by okkwon** [comment]
The dependency on mlir-hlo is gone away in the IREE repo. A next sync will remove it and we can test it again.
