### ISSUE TITLE
[CUDA] Random deadlocks when benchmarking E2E JAX models

### ISSUE THREAD

**Issue by mariecwhite** [openxla/openxla-pjrt-plugin#203]
When benchmarking JAX models with the `iree_cuda` pjrt plugin, execution deadlocks randomly at these points (usually at the first iteration but sometimes at the Nth iteration):
- https://github.com/iree-org/iree-samples/blob/mariecwhite-pjrt/iree-jax/benchmark/benchmark_model.py#L83
- https://github.com/iree-org/iree-samples/blob/mariecwhite-pjrt/iree-jax/benchmark/benchmark_model.py#L90
- https://github.com/iree-org/iree-samples/blob/mariecwhite-pjrt/iree-jax/benchmark/benchmark_model.py#L92

To reproduce:
```
git clone --branch mariecwhite-pjrt https://github.com/iree-org/iree-samples.git
./iree-jax/benchmark/benchmark_all_iree_pjrt.sh "gpu" "output.json"
```

On a docker image, execution deadlocks every time. To reproduce:
```
docker build --file "oobi/build_tools/docker/dockerfiles/cuda11.8-cudnn8.6.Dockerfile" --tag "cuda11.8-cudnn8.6" "oobi/build_tools/docker/context"
docker run --gpus all --mount="type=bind,src="${PWD}",target=/work" --workdir="/work" "cuda11.8-cudnn8.6:latest" ./iree-jax/benchmark/benchmark_all_iree_pjrt.sh "gpu" "output.json"

```

**Comment by jpienaar** [comment]
Could you grab a stack trace?

**Comment by mariecwhite** [comment]
Here's a trace when I cancel the program:

```
--- BERT_LARGE 47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch32 -------------------------------------
Downloaded https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_32/input_0.npy to /tmp/oobi/cache/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_32/input_0.npy
Downloaded https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_32/input_1.npy to /tmp/oobi/cache/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_32/input_1.npy
Downloaded https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_32/output_0.npy to /tmp/oobi/cache/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_32/output_0.npy
[IREE-PJRT] DEBUG: Using IREE compiler binary: /home/mariewhite/github/iree-samples/github/pjrt.venv/lib/python3.10/site-packages/iree/compiler/_mlir_libs/libIREECompiler.so
[IREE-PJRT] DEBUG: Compiler Version: 20230620.558 @ 89a41d9fb6b9ec25fafbffcd50c5fb0ed1182369 (API version 1.2)
[IREE-PJRT] DEBUG: Partitioner was not enabled. The partitioner can be enabled by setting the 'PARTITIONER_LIB_PATH' config var ('IREE_PJRT_PARTITIONER_LIB_PATH' env var)
[IREE-PJRT] DEBUG: CUDA driver created
Creating model BERT_LARGE.
Some weights of FlaxBertModel were not initialized from the model checkpoint at bert-large-uncased and are newly initialized: {('pooler', 'dense', 'kernel'), ('pooler', 'dense', 'bias')}
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Created model.
Placing input date to device.
Completed placing input date to device.
Jitting function.
Completed jitting function.
Starting warmup.
Running jitted function.
^CTraceback (most recent call last):
  File "/home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py", line 216, in <module>
    p.join()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
^CException ignored in atexit callback: <function _exit_function at 0x7fedccfa6950>
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt: 
```

We run the benchmark in a child process so that each benchmark run is isolated. I'll update with a trace when running in the same process.

**Comment by mariecwhite** [comment]
Looking at my processes, there are dozens of benchmarks still running. Seems something is not shutting down cleanly.

```
mariewh+ 2620468 99.6  0.4 175836776 417680 ?    Sl   Jun13 13125:23 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=50
mariewh+ 2621804 99.6  0.4 175812720 397908 ?    Sl   Jun13 13119:01 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2622441 99.6  0.4 175812724 398984 ?    Sl   Jun13 13114:42 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2623070 99.6  0.4 175812744 399220 ?    Sl   Jun13 13113:04 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2626605 99.6  0.4 174554408 397988 ?    Sl   Jun13 13108:35 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2635683 99.6  0.4 174554404 398108 ?    Sl   Jun13 13090:16 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2640141 99.6  0.4 177656056 407448 ?    Sl   Jun13 13071:50 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2640801 99.6  0.4 177656076 405052 ?    Sl   Jun13 13069:42 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --iterations=3
mariewh+ 2654613 99.6  0.4 174554204 405948 ?    Sl   Jun13 13011:21 python3 benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --warmup_iterations=2 --iterations=5 -o /tmp/jax.json
mariewh+ 2654869 99.6  0.4 172772252 397012 ?    Sl   Jun13 13010:48 python3 benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --warmup_iterations=2 --iterations=5 -o /tmp/jax.json
mariewh+ 3624716  0.1  0.5 172729480 485092 pts/1 Sl  Jun21   2:02 python benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=/tmp/pjrt.json --cache_dir=/tmp/cache
mariewh+ 3687199  0.0  2.8 174667684 2462268 pts/1 Sl Jun21   1:29 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch2048 --device=iree_cuda --output_path=/tmp/test.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3711064  0.1  0.6 172772548 539836 pts/2 Sl  Jun21   1:26 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch8 --device=iree_cuda --output_path=/tmp/p1.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3735633  0.1  2.8 174667008 2482764 pts/2 Sl Jun21   1:28 python /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch2048 --device=iree_cuda --output_path=/tmp/t2.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3872744  0.6  0.5 172715300 491812 pts/1 Sl  00:36   1:11 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3887024  0.9  1.2 173362284 1075996 pts/1 Sl 01:03   1:24 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch64 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3892533  0.8  0.6 172799784 582484 pts/1 Sl  01:19   1:10 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3926194  1.3  1.4 173714308 1274668 pts/1 Sl 01:45   1:26 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch256 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3929945  1.1  0.6 172800836 585260 pts/1 Sl  01:53   1:07 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch1 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3955098  1.2  2.8 174666904 2472344 pts/1 Sl 02:05   1:09 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=aff75509-4420-40a8-844e-dbfc48494fe6-MODEL_RESNET50-fp32-JAX-3x224x224xf32-batch2048 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3958217  1.3  7.7 181343724 6775232 pts/1 Sl 02:15   1:02 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch1 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3963381  1.3  7.7 181322016 6757020 pts/1 Sl 02:19   1:03 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch1 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3967891  1.4  7.7 181338372 6766920 pts/1 Sl 02:21   1:03 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch1 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 3994338  1.1  2.5 174470456 2210096 pts/1 Sl 02:42   0:35 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch32 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
mariewh+ 4001379  0.0  0.0   7892  3912 pts/1    S+   03:19   0:00 /bin/bash ./iree-jax/benchmark/benchmark_all_iree_pjrt.sh gpu output.json
mariewh+ 4008663 25.7  7.7 181344040 6823212 pts/1 Sl+ 03:30   1:04 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch16 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache --run_in_process
mariewh+ 4008675  0.0  0.1 952640 97468 pts/1    Sl+  03:30   0:00 python3 /home/mariewhite/github/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch16 --device=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache --run_in_process
```

**Comment by mariecwhite** [comment]
Here are a couple of traces when I see a deadlock at https://github.com/iree-org/iree-samples/blob/mariecwhite-pjrt/iree-jax/benchmark/benchmark_model.py#L83. There are two processes created:

```
$ sudo strace -s 99 -ffp 4014927
strace: Process 4014927 attached with 2 threads
[pid 4014928] accept4(8,  <unfinished ...>
[pid 4014927] restart_syscall(<... resuming interrupted read ...>) = -1 ETIMEDOUT (Connection timed out)
[pid 4014927] futex(0x55bb2e8552b0, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=2499139, tv_nsec=130732166}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
[pid 4014927] futex(0x55bb2e8552b0, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=2499140, tv_nsec=131097066}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
[pid 4014927] futex(0x55bb2e8552b0, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=2499141, tv_nsec=131410656}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
[pid 4014927] futex(0x55bb2e8552b0, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=2499142, tv_nsec=131713885}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
[pid 4014927] futex(0x55bb2e8552b0, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=2499143, tv_nsec=132097342}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
```

```
$ sudo strace -s 99 -ffp 4014915
strace: Process 4014915 attached with 5 threads
[pid 4014935] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 4018935] futex(0x7fd2f13ff910, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 4018934, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid 4014934] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 4014915] futex(0x7fd2f0bfe910, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 4018935, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
[pid 4018934] futex(0x55bb315af910, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 4014935] <... restart_syscall resumed>) = 0
[pid 4014935] poll([{fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=15, events=POLLIN}, {fd=16, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=20, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}], 11, 100) = 0 (Timeout)
[pid 4014935] poll([{fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=15, events=POLLIN}, {fd=16, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=20, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}], 11, 100) = 0 (Timeout)
[pid 4014935] poll([{fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=15, events=POLLIN}, {fd=16, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=20, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}], 11, 100) = 0 (Timeout)
[pid 4014935] poll([{fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=15, events=POLLIN}, {fd=16, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=20, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}], 11, 100) = 0 (Timeout)
[pid 4014935] poll([{fd=13, events=POLLIN}, {fd=14, events=POLLIN}, {fd=15, events=POLLIN}, {fd=16, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=20, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}], 11, 100) = 0 (Timeout)
```

**Comment by stellaraccident** [comment]
There is a "flag" here which outputs a lot of tracing information. May or may not be useful to get.

Would be good to know if it is hanging on a read of a result or a shutdown.

**Comment by ramiro050** [comment]
I seem to be unable to recreate the behavior in the docker. When running in the docker,

```
JAX_PLATFORMS=iree_cuda python /work/iree-samples/iree-jax/benchmark/benchmark_model.py --benchmark_id=47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch32  --devi
ce=iree_cuda --output_path=output.json --iterations=50 --cache_dir=/tmp/oobi/cache
```

the program hangs [during model creation](https://github.com/iree-org/iree-samples/blob/00493f90916f43688837dd94bce8e129c612a479/iree-jax/benchmark/benchmark_model.py#L62). In the plugin, the hang is happening at:

https://github.com/openxla/openxla-pjrt-plugin/blob/b5e30d6352e8e17cbcc945eec2ce4872ddfca46a/iree/integrations/pjrt/common/iree_compiler.cc#L128

The hang happens during the first iteration.

`openxla-pjrt-plugin` version: 38a2960409cdb1d351d9fc9d756630e6a46412a6

**Comment by stellaraccident** [comment]
Probably an excessively long compile vs outright hang. Getting the input to the compiler team would be the thing to do.

**Comment by ramiro050** [comment]
> Probably an excessively long compile vs outright hang. Getting the input to the compiler team would be the thing to do.

Yeah, I should have the IR soon. It might be something similar to https://github.com/openxla/iree/issues/14067

**Comment by mariecwhite** [comment]
JAX models are being benchmarked in the IREE repo using the AOT flow (mlir -> iree-compile -> iree-benchmark-module). That particular model takes about 75 seconds to compile. Here are the compilation time stats:

![image](https://github.com/openxla/openxla-pjrt-plugin/assets/5143063/1e1ad752-e759-4559-a965-082fea9d1247)

**Comment by ramiro050** [comment]
I've opened a bug for Resnet50, which also is taking a long time to compile (running for 10+ minutes without termination): https://github.com/openxla/iree/issues/14245

**Comment by ramiro050** [comment]
Figured out the reason for the deadlock. Currently on the `iree_cuda` backend, [waiting on a semaphore is a no-op](https://github.com/openxla/iree/blob/d37ccadaabf78d80e790e5b111a80a3c0cfff15e/runtime/src/iree/hal/drivers/cuda/event_semaphore.c#L100). This means there is no synchronization between [these two `EventInstance`s](https://github.com/openxla/openxla-pjrt-plugin/blob/f7538e2dd9134f24019f4654092b448da0944c8f/iree/integrations/pjrt/common/api_impl.cc#L633-L637), leading to deadlocks when the events trigger their callbacks in the wrong order.

@antiagainst is currently working on adding semaphore support: https://github.com/openxla/iree/issues/4727.

**Comment by antiagainst** [comment]
Just replying to the above: yes, I've uploaded a proper semaphore impl in CUDA: https://github.com/openxla/iree/pull/14426; under review now.

**Comment by mariecwhite** [comment]
I'm still seeing deadlocks in IREE release 20230728.596 on GPU. CPU is working, though it's outputting some errors `loc("-":0:0): error: invalid section ID: 32` that may not be errors.

**Comment by jpienaar** [comment]
Yes that error is when it's trying to get the output sharding and for some reason that's reported.

**Comment by jpienaar** [comment]
(previously it was just returning unimplemented here, so no degradation with that error)

**Comment by ramiro050** [comment]
> I'm still seeing deadlocks in IREE release 20230728.596 on GPU. 

Yes, the changes Lei is working on are currently in the `experimental` directory. Until the new HAL CUDA implementation replaces the old one, the deadlock will keep on happening. More details on the overall progress for the new HAL backend here: https://github.com/openxla/iree/issues/13245
